// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export { SystemLog } from './schematas/system-log.js';
export { SystemLogList } from './schematas/system-log-list.js';
