// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export { JobAuditLog } from './schematas/job-audit-log.js';
export { JobAuditLogList } from './schematas/job-audit-log-list.js';
