// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class AdminAuditLog {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AdminAuditLog {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAdminAuditLog(bb:flatbuffers.ByteBuffer, obj?:AdminAuditLog):AdminAuditLog {
  return (obj || new AdminAuditLog()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAdminAuditLog(bb:flatbuffers.ByteBuffer, obj?:AdminAuditLog):AdminAuditLog {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AdminAuditLog()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

username():string|null
username(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
username(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

action():string|null
action(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
action(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

details():string|null
details(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
details(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

ts():string|null
ts(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
ts(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

tsUnixMs():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startAdminAuditLog(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addId(builder:flatbuffers.Builder, id:bigint) {
  builder.addFieldInt64(0, id, BigInt('0'));
}

static addUsername(builder:flatbuffers.Builder, usernameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, usernameOffset, 0);
}

static addAction(builder:flatbuffers.Builder, actionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, actionOffset, 0);
}

static addDetails(builder:flatbuffers.Builder, detailsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, detailsOffset, 0);
}

static addTs(builder:flatbuffers.Builder, tsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, tsOffset, 0);
}

static addTsUnixMs(builder:flatbuffers.Builder, tsUnixMs:bigint) {
  builder.addFieldInt64(5, tsUnixMs, BigInt('0'));
}

static endAdminAuditLog(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAdminAuditLog(builder:flatbuffers.Builder, id:bigint, usernameOffset:flatbuffers.Offset, actionOffset:flatbuffers.Offset, detailsOffset:flatbuffers.Offset, tsOffset:flatbuffers.Offset, tsUnixMs:bigint):flatbuffers.Offset {
  AdminAuditLog.startAdminAuditLog(builder);
  AdminAuditLog.addId(builder, id);
  AdminAuditLog.addUsername(builder, usernameOffset);
  AdminAuditLog.addAction(builder, actionOffset);
  AdminAuditLog.addDetails(builder, detailsOffset);
  AdminAuditLog.addTs(builder, tsOffset);
  AdminAuditLog.addTsUnixMs(builder, tsUnixMs);
  return AdminAuditLog.endAdminAuditLog(builder);
}
}
