// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { AdminAuditLog } from '../schematas/admin-audit-log.js';


export class AdminAuditLogList {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AdminAuditLogList {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAdminAuditLogList(bb:flatbuffers.ByteBuffer, obj?:AdminAuditLogList):AdminAuditLogList {
  return (obj || new AdminAuditLogList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAdminAuditLogList(bb:flatbuffers.ByteBuffer, obj?:AdminAuditLogList):AdminAuditLogList {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AdminAuditLogList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

logs(index: number, obj?:AdminAuditLog):AdminAuditLog|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new AdminAuditLog()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

logsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startAdminAuditLogList(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addLogs(builder:flatbuffers.Builder, logsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, logsOffset, 0);
}

static createLogsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startLogsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endAdminAuditLogList(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishAdminAuditLogListBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedAdminAuditLogListBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createAdminAuditLogList(builder:flatbuffers.Builder, logsOffset:flatbuffers.Offset):flatbuffers.Offset {
  AdminAuditLogList.startAdminAuditLogList(builder);
  AdminAuditLogList.addLogs(builder, logsOffset);
  return AdminAuditLogList.endAdminAuditLogList(builder);
}
}
