// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { SystemLog } from '../schematas/system-log.js';


export class SystemLogList {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SystemLogList {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSystemLogList(bb:flatbuffers.ByteBuffer, obj?:SystemLogList):SystemLogList {
  return (obj || new SystemLogList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSystemLogList(bb:flatbuffers.ByteBuffer, obj?:SystemLogList):SystemLogList {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SystemLogList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

logs(index: number, obj?:SystemLog):SystemLog|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new SystemLog()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

logsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startSystemLogList(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addLogs(builder:flatbuffers.Builder, logsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, logsOffset, 0);
}

static createLogsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startLogsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endSystemLogList(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishSystemLogListBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedSystemLogListBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createSystemLogList(builder:flatbuffers.Builder, logsOffset:flatbuffers.Offset):flatbuffers.Offset {
  SystemLogList.startSystemLogList(builder);
  SystemLogList.addLogs(builder, logsOffset);
  return SystemLogList.endSystemLogList(builder);
}
}
