// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class SystemLog {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SystemLog {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSystemLog(bb:flatbuffers.ByteBuffer, obj?:SystemLog):SystemLog {
  return (obj || new SystemLog()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSystemLog(bb:flatbuffers.ByteBuffer, obj?:SystemLog):SystemLog {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SystemLog()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

level():string|null
level(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
level(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

component():string|null
component(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
component(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

message():string|null
message(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
message(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

ts():string|null
ts(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
ts(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

tsUnixMs():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startSystemLog(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addId(builder:flatbuffers.Builder, id:bigint) {
  builder.addFieldInt64(0, id, BigInt('0'));
}

static addLevel(builder:flatbuffers.Builder, levelOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, levelOffset, 0);
}

static addComponent(builder:flatbuffers.Builder, componentOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, componentOffset, 0);
}

static addMessage(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, messageOffset, 0);
}

static addTs(builder:flatbuffers.Builder, tsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, tsOffset, 0);
}

static addTsUnixMs(builder:flatbuffers.Builder, tsUnixMs:bigint) {
  builder.addFieldInt64(5, tsUnixMs, BigInt('0'));
}

static endSystemLog(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSystemLog(builder:flatbuffers.Builder, id:bigint, levelOffset:flatbuffers.Offset, componentOffset:flatbuffers.Offset, messageOffset:flatbuffers.Offset, tsOffset:flatbuffers.Offset, tsUnixMs:bigint):flatbuffers.Offset {
  SystemLog.startSystemLog(builder);
  SystemLog.addId(builder, id);
  SystemLog.addLevel(builder, levelOffset);
  SystemLog.addComponent(builder, componentOffset);
  SystemLog.addMessage(builder, messageOffset);
  SystemLog.addTs(builder, tsOffset);
  SystemLog.addTsUnixMs(builder, tsUnixMs);
  return SystemLog.endSystemLog(builder);
}
}
